options:
  formatter: stylish
  convention-explanation: 'SASS Standard - Protime adjustment'
files:
  include:
    - 'drool/**/*.s+(a|c)ss'
    - 'drool-lib/**/*.s+(a|c)ss'
    - 'app/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 2

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  declarations-before-nesting: 2
  no-color-keywords: 2
  no-color-literals: 2
  no-css-comments: 0
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 2
  no-important: 0 # Should be an error, but requires some changes on legacy files
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements:
    - 2
    - allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false

  no-trailing-zero: 2
  no-transition-all: 0 # Should be an error, performance impact and unpredictable
  no-url-protocols: 0
  no-url-domains: 0
  no-vendor-prefixes: 2
  no-warn: 2
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 0 # NO warning, this is unusable because of the amount of warnings, we want to set this as an error once all components have been converted to CSS modules
    - convention: 'camelcase'

  function-name-format: 2
  id-name-format: 0
  mixin-name-format: 2
  placeholder-name-format:
    - 1
    - convention: 'camelcase'

  variable-name-format: 0
  clean-import-paths: 0

  # Style Guide
  bem-depth: 0
  border-zero:
    - 2
    - convention: 'none'

  brace-style:
    - 2
    - style: '1tbs'
      allow-single-line: true

  empty-args: 2
  hex-length: 2
  hex-notation: 2
  indentation:
    - 2
    - size: 4

  leading-zero: 2
  nesting-depth:
    - 2
    - max-depth: 5

  property-sort-order:
    - 2
    - order: 'concentric'

  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 2
