---
linters:
  BangFormat:
    enabled: true
  DeclarationOrder:
    enabled: true
  DuplicateProperty:
    enabled: true
  EmptyLineBetweenBlocks:
    enabled: true
  EmptyRule:
    enabled: true
  HexValidation:
    enabled: true
  IdSelector:
    enabled: false
  ImportPath:
    enabled: true
  ImportantRule:
    enabled: false
  Indentation:
    enabled: true
  LeadingZero:
    enabled: false
  MergeableSelector:
    enabled: true
  NameFormat:
    enabled: false
  PlaceholderInExtend:
    enabled: false
  PropertySortOrder:
    enabled: true
  PropertySpelling:
    enabled: true
  QualifyingElement:
    enabled: false
  Shorthand:
    enabled: true
  SelectorFormat:
    enabled: false
  SingleLinePerProperty:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceAfterPropertyName:
    style: one_space
  SpaceAfterComment:
    enabled: true
  SpaceAfterVariableName:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  SpaceBetweenParens:
    enabled: false
  StringQuotes:
    enabled: false
  TrailingZero:
    enabled: true
  TrailingSemicolon:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VendorPrefix:
    enabled: false
  ZeroUnit:
    enabled: false
