" break with the busted old vi junk
" must be first
set nocompatible
filetype off

" Clone Vundle (Package Manager)
" $ git clone https://github.com/VundleVim/Vundle.vim.git $XDG_CONFIG_HOME/vim/bundle/Vundle.vim

" XDG Paths
" mkdir -p $XDG_CACHE_HOME/vim/{undo,swap,backup} $XDG_CONFIG_HOME/vim
set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_STATE_HOME/vim/backup,~/,/tmp
set undodir=$XDG_STATE_HOME/vim/undo,~/,/tmp
set viminfo+=n$XDG_STATE_HOME/vim/viminfo
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
set packpath=$XDG_CONFIG_HOME/vim,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"


" Use Bash shell, Avoid zsh/fish shell issues
set shell=/bin/bash

""""""""""""""""""""""""""""""""""""""""
" Plugins
""""""""""""""""""""""""""""""""""""""""

" vundle plugins (Move to XDG Path)
set rtp+=$XDG_CONFIG_HOME/vim/bundle/Vundle.vim
call vundle#rc("$XDG_CONFIG_HOME/vim/bundle")

" vundle repo
Bundle 'gmarik/Vundle.vim'

" Color/Style Schemes
Plugin 'benjaminwhite/Benokai'
Plugin 'bling/vim-airline'        " Statusline
Plugin 'vim-airline/vim-airline-themes' " Themes
Plugin 'gregsexton/matchtag'

" Productivity
Plugin 'kien/ctrlp.vim'
Plugin 'scrooloose/nerdtree'      " Tree Style Dirs
Plugin 'tomtom/tcomment_vim'

" Languages
Plugin 'ap/vim-css-color'

" FZF (Requires FZF Installed)
Plugin 'junegunn/fzf'

"Plugin 'Autoclose'
Plugin 'chiel92/vim-autoformat'
Plugin 'eslint/eslint'
Plugin 'evidens/vim-twig'
Plugin 'othree/html5.vim'
Plugin 'ShowPairs'

" Syntax Languages
Plugin 'leafgarland/typescript-vim'
Plugin 'fatih/vim-go'
Plugin 'elzr/vim-json'
Plugin 'hail2u/vim-css3-syntax'
Plugin 'hdima/python-syntax'
Plugin 'isruslan/vim-es6'
Plugin 'kien/rainbow_parentheses.vim'
Plugin 'mustache/vim-mustache-handlebars'
Plugin 'mxw/vim-jsx'
Plugin 'pangloss/vim-javascript'
Plugin 'plasticboy/vim-markdown'
Plugin 'StanAngeloff/php.vim'
Plugin 'stephpy/vim-yaml'
Plugin 'ekalinin/dockerfile.vim'

" misc
Bundle "vim-scripts/gitignore"
Plugin 'nathanaelkane/vim-indent-guides'

" error handling
Bundle "scrooloose/syntastic"


let g:syntastic_aggregate_errors = 1
let g:syntastic_check_on_open = 0

" Editing nginx files
au BufRead,BufNewFile /etc/nginx/*,/usr/local/nginx/conf/*,nginx.conf if &ft == '' | setfiletype nginx | endif
" autocmd BufRead,BufNewFile /etc/nginx/sites-*/* setfiletype conf


autocmd BufRead,BufNewFile *.conf setf dosini

" For Match Tag Always
let g:rbpt_loadround = 1

" For vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" Indent Guides
let g:indent_guides_enable_on_vim_startup = 1
let g:indent_guides_auto_colors = 0
autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=red   ctermbg=235
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green ctermbg=237

let g:indentLine_setColors = 0
let g:indentLine_color_term = 239
" let g:indentLine_char = 'c'

" For vim-markdown
autocmd BufNewFile,BufReadPost *.md set filetype=markdown

" custom file ignores
let g:ctrlp_custom_ignore = {
    \ 'dir':  '\.git$\|\.hg$\|\.svn$\|bower_components$\|dist$\|node_modules$\|project_files$\|test$',
    \ 'file': '\.exe$\|\.so$\|\.dll$\|\.pyc$' }

" rainbow parentheses
let g:rbpt_colorpairs = [
    \ ['brown',       'RoyalBlue3'],
    \ ['Darkblue',    'SeaGreen3'],
    \ ['darkgray',    'DarkOrchid3'],
    \ ['darkgreen',   'firebrick3'],
    \ ['darkcyan',    'RoyalBlue3'],
    \ ['darkred',     'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['brown',       'firebrick3'],
    \ ['gray',        'RoyalBlue3'],
    \ ['black',       'SeaGreen3'],
    \ ['darkmagenta', 'DarkOrchid3'],
    \ ['Darkblue',    'firebrick3'],
    \ ['darkgreen',   'RoyalBlue3'],
    \ ['darkcyan',    'SeaGreen3'],
    \ ['darkred',     'DarkOrchid3'],
    \ ['red',         'firebrick3'],
    \ ]
let g:rbpt_max = 16
let g:rbpt_loadcmd_toggle = 1


autocmd VimEnter * RainbowParenthesesToggle
autocmd Syntax * RainbowParenthesesLoadRound
autocmd Syntax * RainbowParenthesesLoadSquare
autocmd Syntax * RainbowParenthesesLoadBraces

""""""""""""""""""""""""""""""""""""""""
" General VIM
""""""""""""""""""""""""""""""""""""""""

" Auto strip trailing white space when :w
autocmd BufWritePre * :%s/\s\+$//e

" mouse selections will move window down for long selections
set mouse=a

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" show line numbers
set number

" show lines in lower right
set ruler

" don't wrap lines ever
set nowrap

" Set to auto read when a file is changed from the outside
set autoread
set updatetime=200000  " Check every 20 seconds

" global text columns
" set textwidth=80

" don't automatically break long lines unless they are new
"set formatoptions+=l

" detect file type, turn on that type's plugins and indent preferences
" Turned off -- This was annoying when copy/pasting causes indent problems
" filetype plugin on
" filetype plugin indent on

" Show matching brackets when text indicator is over them
set showmatch

" How many tenths of a second to blink when matching brackets
set mat=2

" No annoying sound on errors
set noerrorbells
set novisualbell
set t_vb=
set tm=500

" allow background buffers
set hidden

" global tab settinga
set tabline=2
set tabstop=2
set softtabstop=2
set shiftwidth=2  " indent size
set expandtab     " use space instead of tab

autocmd Filetype php setlocal tabstop=4
autocmd Filetype nginx setlocal tabstop=2

" ignore these nonsense files
set wildignore=*.swp,*.bak,*.pyc,*.class,*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx

" Return to last edit position when opening files
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "norm/al! g`\"" |
     \ endif

" Remember info about open buffers on close
set viminfo^=%

" no backups, please!
set nobackup
set noswapfile

" keep a longer history
set history=1000

" enable folding
"set foldmethod=indent
"set foldlevel=99

" make file/command tab completion useful
set wildmode=list:longest

" clipboard fusion!
set clipboard^=unnamed clipboard^=unnamedplus

""""""""""""""""""""""""""""""""""""""""
" Hotkeys
""""""""""""""""""""""""""""""""""""""""
" Not working w/emulator
" Map Ctrl+/ to toggle comments
" nmap <C-/> :NERDCommentToggle<CR>
" vmap <C-/> :NERDCommentToggle<CR>

" Mode Mappings
" The 'r' represents non-recursive
" :map   :noremap  :unmap     Normal, Visual, Select, Operator-pending
" :nmap  :nnoremap :nunmap    Normal
" :vmap  :vnoremap :vunmap    Visual and Select
" :smap  :snoremap :sunmap    Select
" :xmap  :xnoremap :xunmap    Visual
" :omap  :onoremap :ounmap    Operator-pending
" :map!  :noremap! :unmap!    Insert and Command-line
" :imap  :inoremap :iunmap    Insert
" :lmap  :lnoremap :lunmap    Insert, Command-line, Lang-Arg
" r:cmap :cnoremap :cunmap    Command-line
" :tmap  :tnoremap :tunmap    Terminal-Job
"o
" Examples
" .. :nmap x dd  -- Map x to dd in normal mode
" .. :inoremap jk <esc> -- Maps  'jk' to <esc> key, exits insert mode


" Map Shift+Tab to unindent
nnoremap <S-Tab> <<
inoremap <S-Tab> <C-o><<

" Map Ctrl+Backspace to delete a subword
nmap <C-BS> dB
imap <C-BS> <C-o>dB

" Ctrl+Shift Left/Right is also Home/End since Alt doesnt work w/emulator
nmap <C-S-Right> $
imap <C-S-Right> <C-o>$
nmap <C-S-Left> 0
imap <C-S-Left> <C-o>0

" Nerd Tree
map <C-n> :NERDTreeToggle<CR>

inoremap <C+y> <c-o>:redo</cr>

" easier window navigation
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" Not needed with set clipboard and clipboard set
"vnoremap <C-Shift-c> "+y
vnoremap <C+Sihft-v> "+p

""""""""""""""""""""""""""""""""""""""""
" Searching
""""""""""""""""""""""""""""""""""""""""

" show search matches as you type
set incsearch

" clear the search buffer when hitting return
nnoremap <CR> :nohlsearch<cr>

" Ignore case when searching
set ignorecase

" When searching try to be smart about cases
set smartcase

" highlight search results
set hlsearch

""""""""""""""""""""""""""""""""""""""""
" Aestehtics
""""""""""""""""""""""""""""""""""""""""

" keep cursor somewhat centered
set scrolloff=3

" highlight current line
set cursorline

" invert and bold status line
set highlight=sbr

" enable syntax highlighting
syntax on

"tell the term has 256 colors
set t_Co=256

colorscheme Benokai
set guifont=Inconsolata\ Medium\ 10

" highlight col 80
"set colorcolumn=80
"highlight ColorColumn guibg=#333

" extra whitespace sucks, make it RED
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/


" Toggle line numbers (both absolute and relative) with F2, and show a message.
function! ToggleLineNumbers()
  if &number
    set nonumber norelativenumber
    echo "Line numbers OFF"
  else
    set number relativenumber
    echo "Line numbers ON"
  endif
endfunction

nnoremap <F2> :call ToggleLineNumbers()<CR>
