#!/bin/bash
# This hook is sourced after a new virtualenv is activated.

proj_name=$(echo $VIRTUAL_ENV|awk -F'/' '{print $NF}')
[ ! -d ~/$PYTHON_PROJECT_HOME/$proj_name ] && mkdir -p ~/$PYTHON_PROJECT_HOME/$proj_name
add2virtualenv ~/$PYTHON_PROJECT_HOME/$proj_name
cd ~/$PYTHON_PROJECT_HOME/$proj_name
